#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Determine which configs to load based on OS
CONFIGS=("install.conf.yaml")  # Base config always loaded

if [ "$(uname)" = "Darwin" ]; then
    CONFIGS+=("install-darwin.conf.yaml")
elif [ "$(uname)" = "Linux" ]; then
    CONFIGS+=("install-linux.conf.yaml")
fi

# Run Dotbot with all applicable configs
for config in "${CONFIGS[@]}"; do
    echo "Loading configuration: ${config}"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${config}" "${@}"
done
